name: Add my own IP to the firewall whitelist
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the firewall rule'
        required: true
        default: ''
      ip:
        description: 'IP Address to whitelist'
        required: true
        default: ''

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Init VPN Connection
        run: echo "Initializing VPN Connection"

  stage2:
    runs-on: ubuntu-latest
    steps:
      - name: Add Firewall Rule
        run: "echo \"Adding Firewall Rule for IP: ${{ github.event.inputs.ip }} with Rule Name: ${{ github.event.inputs.name }}\""

  stage3:
    runs-on: ubuntu-latest
    steps:
      - name: Logging to Audit Log
        run: echo "Logging to Audit Log"
